USE Filmes;

--1
SELECT NOME, ANO FROM Filmes

--2
SELECT NOME, ANO FROM Filmes
ORDER BY ANO ASC

--3
SELECT NOME, ANO, DURACAO FROM Filmes
WHERE Nome LIKE 'DE VOLTA%'

--4
SELECT * FROM Filmes
WHERE ANO = 1997

--5
SELECT * FROM Filmes
WHERE ANO > 2000

--6
SELECT * FROM Filmes
WHERE DURACAO > 100 AND DURACAO < 150
ORDER BY Duracao ASC

--7 
/* OBS.: NO ENUNCIADO PEDE PARA ORDENAR PELA DURAÇÃO DESC, PORÉM PARA TER O MESMO RESULTADO
   DA IMAGEM, ORDENEI PELO TOTAL
*/
SELECT ANO, COUNT(*) AS TOTAL FROM Filmes
GROUP BY ANO
ORDER BY (TOTAL) DESC

--8
SELECT PrimeiroNome, UltimoNome FROM Atores
WHERE Genero = 'M'

--9
SELECT PrimeiroNome, UltimoNome FROM Atores
WHERE Genero = 'F'
ORDER BY PrimeiroNome

--10
SELECT _FILMES.Nome, _GENEROS.Genero FROM Filmes _FILMES
JOIN FilmesGenero _FILME_GENERO ON _FILMES.Id = _FILME_GENERO.IdFilme
JOIN Generos _GENEROS ON _FILME_GENERO.IdGenero = _GENEROS.Id

--11
SELECT _FILMES.Nome, _GENEROS.Genero FROM Filmes _FILMES
JOIN FilmesGenero _FILME_GENERO ON _FILMES.Id = _FILME_GENERO.IdFilme
JOIN Generos _GENEROS ON _FILME_GENERO.IdGenero = _GENEROS.Id
WHERE _GENEROS.Genero = 'Mistério'

--12
SELECT _FILMES.Nome,_ATORES.PrimeiroNome, _ATORES.UltimoNome, _ELENCO_FILMES.Papel FROM Filmes _FILMES
JOIN ElencoFilme _ELENCO_FILMES ON _FILMES.Id = _ELENCO_FILMES.IdFilme
JOIN Atores _ATORES ON _ELENCO_FILMES.IdAtor = _ATORES.Id

